// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmImLqLpt1z-EsQBfEMwZdVg74xxxYEE',
    appId: '1:954689905286:web:346772881ccdc7fec9a707',
    messagingSenderId: '954689905286',
    projectId: 'signin-40c9b',
    authDomain: 'signin-40c9b.firebaseapp.com',
    storageBucket: 'signin-40c9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyvqDZ51LyfGZVoU5bnZViieihjUE4U9I',
    appId: '1:954689905286:android:3fdf804c170e39bac9a707',
    messagingSenderId: '954689905286',
    projectId: 'signin-40c9b',
    storageBucket: 'signin-40c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXumRVRQbVaOq8KW4PaxIsh0BhW9CV3pE',
    appId: '1:954689905286:ios:5b83bdb08ad46b0bc9a707',
    messagingSenderId: '954689905286',
    projectId: 'signin-40c9b',
    storageBucket: 'signin-40c9b.appspot.com',
    iosBundleId: 'com.example.gooleSign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmImLqLpt1z-EsQBfEMwZdVg74xxxYEE',
    appId: '1:954689905286:web:a672e652d7f7d18ac9a707',
    messagingSenderId: '954689905286',
    projectId: 'signin-40c9b',
    authDomain: 'signin-40c9b.firebaseapp.com',
    storageBucket: 'signin-40c9b.appspot.com',
  );

}